import WorkNotices from './work-notices'
import ToDoList from './to-do-list'
import MuchUsedMenu from './much-used-menu'
import FinancialCondition from './financial-condition'
import CapitalAccountCondition from './capital-account-condition'
import VardSwiper from './vard-swiper'
import GpmcCondition from './gpmc-condition'
import CntcCondition from './cntc-condition'
import TaskCenterCard from './task-center-card'
export default { WorkNotices, ToDoList, MuchUsedMenu, FinancialCondition, VardSwiper, CapitalAccountCondition, GpmcCondition, CntcCondition, TaskCenterCard }
